name: Weekly Movie Scraper

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add movies.json
          if ! git diff --cached --quiet; then
            git commit -m "Update movies.json [skip ci]"
          else
            echo "No changes detected"
            exit 0
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/movies-json
          commit-message: "Update movies.json [skip ci]"
          title: "Weekly Movie Update"
          body: "Automated update of movies.json by GitHub Actions"
          base: main
