name: Video Link Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 playwright PyQt5
          playwright install chromium

      - name: Run video scraper
        run: python scraper_videos.py

      - name: Commit and Push results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add video_links.json
          if ! git diff --cached --quiet; then
            git commit -m "Update video_links.json [skip ci]"
            git push
          else
            echo "No changes detected"
          fi
